"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { fadeUp, stagger } from "@/lib/animations";

interface ContentItem {
  id: string; type: string; title: string; body: string; status: string;
  tags: string[]; targetDate?: string; publishedAt?: string; createdAt: string;
}

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
const statusColors: Record<string, string> = {
  IDEA: "bg-white/[0.03] text-[#A0988E]", DRAFTING: "bg-white/[0.05] text-[#EDE8E0]",
  REVIEW: "bg-white/[0.06] text-[#EDE8E0]", APPROVED: "bg-white/[0.08] text-[#EDE8E0]",
  PUBLISHED: "bg-white/[0.1] text-[#EDE8E0]",
};

export default function ContentPage() {
  const [items, setItems] = useState<ContentItem[]>([]);
  const [tab, setTab] = useState("all");

  useEffect(() => { fetchContent(); }, []);

  async function fetchContent() {
    try { const res = await fetch(`${API}/api/content?limit=100`); if (res.ok) setItems(await res.json()); } catch { /* */ }
  }

  const filtered = tab === "all" ? items : items.filter((i) => i.type === tab);

  return (
    <motion.div
      className="space-y-10"
      initial="hidden"
      animate="visible"
      variants={stagger}
    >
      <motion.div variants={fadeUp}>
        <h1 className="text-3xl font-semibold tracking-tight text-[#EDE8E0]">Content</h1>
        <p className="text-[#A0988E] mt-2 text-sm">Content generated by Nova.</p>
      </motion.div>

      <motion.div variants={fadeUp}>
        <Tabs value={tab} onValueChange={setTab}>
          <TabsList>
            <TabsTrigger value="all">All</TabsTrigger>
            <TabsTrigger value="LINKEDIN_POST">LinkedIn</TabsTrigger>
            <TabsTrigger value="BLOG_ARTICLE">Blog</TabsTrigger>
            <TabsTrigger value="NEWSLETTER">Newsletter</TabsTrigger>
          </TabsList>
          <TabsContent value={tab} className="mt-8">
            {filtered.length === 0 ? (
              <Card>
                <CardContent className="flex flex-col items-center justify-center py-20 text-center">
                  <p className="text-sm text-[#A0988E] max-w-sm leading-relaxed">
                    No content yet. Ask Quinn to produce content ideas.
                  </p>
                </CardContent>
              </Card>
            ) : (
              <div className="grid gap-3">
                {filtered.map((item, i) => (
                  <motion.div key={item.id} variants={fadeUp} custom={i}>
                    <Card className="glass-card-hover">
                      <CardContent className="p-5">
                        <div className="flex items-start justify-between gap-6">
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 mb-2">
                              <Badge variant="outline" className="text-xs rounded-full">
                                {item.type.replace(/_/g, " ")}
                              </Badge>
                              <Badge variant="outline" className={`${statusColors[item.status] ?? ""} rounded-full`}>
                                {item.status}
                              </Badge>
                            </div>
                            <h3 className="text-sm font-medium text-[#EDE8E0]">{item.title}</h3>
                            <p className="text-sm text-[#A0988E] mt-1.5 line-clamp-2 leading-relaxed">{item.body}</p>
                            {item.tags.length > 0 && (
                              <div className="flex flex-wrap gap-1.5 mt-3">
                                {item.tags.map((tag) => (
                                  <Badge key={tag} variant="secondary" className="text-[10px] rounded-full px-2">
                                    {tag}
                                  </Badge>
                                ))}
                              </div>
                            )}
                          </div>
                          <div className="text-xs text-[#A0988E]/40 shrink-0 pt-1">
                            {new Date(item.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </motion.div>
                ))}
              </div>
            )}
          </TabsContent>
        </Tabs>
      </motion.div>
    </motion.div>
  );
}
