"use client";

import { useEffect, useState } from "react";
import { FileText, Calendar, PenLine } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

interface ContentItem {
  id: string; type: string; title: string; body: string; status: string;
  tags: string[]; targetDate?: string; publishedAt?: string; createdAt: string;
}

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
const statusColors: Record<string, string> = {
  IDEA: "bg-slate-500/10 text-slate-400", DRAFTING: "bg-blue-500/10 text-blue-400",
  REVIEW: "bg-yellow-500/10 text-yellow-400", APPROVED: "bg-green-500/10 text-green-400",
  PUBLISHED: "bg-primary/10 text-primary",
};

export default function ContentPage() {
  const [items, setItems] = useState<ContentItem[]>([]);
  const [tab, setTab] = useState("all");

  useEffect(() => { fetchContent(); }, []);

  async function fetchContent() {
    try { const res = await fetch(`${API}/api/content?limit=100`); if (res.ok) setItems(await res.json()); } catch { /* */ }
  }

  const filtered = tab === "all" ? items : items.filter((i) => i.type === tab);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight"><span className="text-gradient">Content Hub</span></h1>
        <p className="text-muted-foreground mt-1">Content generated by Nova — posts, articles, and campaigns.</p>
      </div>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="bg-muted/50">
          <TabsTrigger value="all">All</TabsTrigger>
          <TabsTrigger value="LINKEDIN_POST">LinkedIn</TabsTrigger>
          <TabsTrigger value="BLOG_ARTICLE">Blog</TabsTrigger>
          <TabsTrigger value="NEWSLETTER">Newsletter</TabsTrigger>
        </TabsList>
        <TabsContent value={tab} className="mt-6">
          {filtered.length === 0 ? (
            <Card className="glass-card">
              <CardContent className="flex flex-col items-center justify-center py-16 text-center">
                <PenLine className="h-12 w-12 text-muted-foreground/30 mb-4" />
                <h3 className="text-lg font-semibold mb-2">No content yet</h3>
                <p className="text-sm text-muted-foreground max-w-sm">Nova hasn&apos;t generated content yet. Ask Quinn to produce content ideas.</p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4">
              {filtered.map((item) => (
                <Card key={item.id} className="glass-card transition-all hover:border-primary/20">
                  <CardContent className="p-5">
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <Badge variant="outline" className="text-xs">{item.type.replace(/_/g, " ")}</Badge>
                          <Badge variant="outline" className={statusColors[item.status] ?? ""}>{item.status}</Badge>
                        </div>
                        <h3 className="font-semibold mt-2">{item.title}</h3>
                        <p className="text-sm text-muted-foreground mt-1 line-clamp-2">{item.body}</p>
                        {item.tags.length > 0 && (
                          <div className="flex flex-wrap gap-1 mt-2">
                            {item.tags.map((tag) => <Badge key={tag} variant="secondary" className="text-[10px]">{tag}</Badge>)}
                          </div>
                        )}
                      </div>
                      <div className="text-xs text-muted-foreground/60 shrink-0">
                        {new Date(item.createdAt).toLocaleDateString()}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
