/**
 * Quinn Decision Framework
 *
 * Every recommendation from Quinn follows this structure to ensure
 * consistent, data-driven decision making.
 */

export type EffortLevel = "LOW" | "MEDIUM" | "HIGH";

export type PriorityLevel = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";

export type AgentNameType =
  | "quinn"
  | "sage"
  | "nova"
  | "atlas"
  | "iris"
  | "helix"
  | "beacon";

/**
 * Every recommendation must include this structure.
 * This is the core of Quinn's decision-making framework.
 */
export interface Recommendation {
  /** What should Quinn do? */
  what: string;
  /** Why? */
  reasoning: string;
  /** What value will this create? */
  expectedImpact: string;
  /** Effort required */
  effort: EffortLevel;
  /** Percentage confidence (0-100) */
  confidenceScore: number;
  /** How will success be measured? */
  successMetrics: string[];
  /** Impact score for Impact × Effort matrix (1-10) */
  impactScore: number;
  /** Effort score for Impact × Effort matrix (1-10) */
  effortScore: number;
  /** Priority quadrant derived from impact × effort */
  quadrant: "quick-win" | "major-project" | "fill-in" | "thankless";
}

/**
 * Agent communication protocol.
 * All inter-agent messages follow this format.
 */
export interface AgentMessage {
  id: string;
  from: AgentNameType;
  to: AgentNameType;
  type: "REQUEST" | "RESPONSE" | "REPORT" | "ALERT";
  subject: string;
  payload: unknown;
  timestamp: Date;
  threadId?: string;
}

/**
 * Agent report structure — each worker produces this for Quinn.
 */
export interface AgentReport {
  agentName: AgentNameType;
  summary: string;
  findings: string[];
  recommendations: Recommendation[];
  actionItems: ActionItem[];
  timestamp: Date;
}

/**
 * An action item generated by any agent.
 */
export interface ActionItem {
  id: string;
  title: string;
  description: string;
  assignedTo: AgentNameType;
  priority: PriorityLevel;
  dueDate?: Date;
  status: "pending" | "in_progress" | "completed" | "cancelled";
  relatedEntityId?: string;
  relatedEntityType?: string;
}

/**
 * Executive briefing structure.
 */
export interface ExecutiveBriefing {
  date: Date;
  type: "daily" | "weekly" | "quarterly";
  title: string;
  summary: string;
  sections: BriefingSection[];
  topPriorities: Recommendation[];
  alerts: Alert[];
  pendingApprovalCount: number;
}

export interface BriefingSection {
  agentName: AgentNameType;
  title: string;
  content: string;
  recommendations: Recommendation[];
  metrics?: Record<string, number | string>;
}

export interface Alert {
  level: "info" | "warning" | "critical";
  title: string;
  message: string;
  agentName: AgentNameType;
  actionRequired: boolean;
}

/**
 * Workflow trigger types.
 */
export type WorkflowType =
  | "daily-briefing"
  | "weekly-priorities"
  | "weekly-report"
  | "quarterly-planning"
  | "research-sweep"
  | "content-generation"
  | "follow-up-check"
  | "analytics-snapshot";

/**
 * Approval request structure sent from agents to the dashboard.
 */
export interface ApprovalRequest {
  type: string;
  title: string;
  description: string;
  content: unknown;
  agentName: AgentNameType;
  priority: PriorityLevel;
  reasoning: string;
  impact: string;
  effort: EffortLevel;
  confidence: number;
  metrics: string[];
  contentItemId?: string;
  expiresAt?: Date;
}

/**
 * WebSocket event types for real-time dashboard updates.
 */
export type WSEventType =
  | "briefing:new"
  | "approval:new"
  | "approval:updated"
  | "agent:status"
  | "workflow:started"
  | "workflow:completed"
  | "alert:new"
  | "analytics:updated";

export interface WSEvent {
  type: WSEventType;
  payload: unknown;
  timestamp: Date;
}
